version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: